name: motrix

services:
  server:
    image: docker.io/motrixapp/motrix-server:2.0.0-beta.39
    environment:
      PUID: "1000"
      PGID: "1000"
      MOTRIX_DATA_DIR: /data
      MOTRIX_TEMP_DIR: /data/tmp
      MOTRIX_PLUGIN_DIR: /data/plugins
      MOTRIX_DEFAULT_SAVE_DIR: /downloads
      MOTRIX_ALLOWED_SAVE_DIRS: /downloads
      MOTRIX_ARIA2_RPC_LISTEN_ALL: "false"
      MOTRIX_MDXP_HOST: 0.0.0.0
      MOTRIX_MDXP_PORT: 16801
      MOTRIX_PUBLIC_URL: ""
      MOTRIX_REMOTE_EXTENSION_ENABLED: "false"
      MOTRIX_REMOTE_EXTENSION_PUBLIC_URL: ""
      MOTRIX_ALLOW_INSECURE_OPERATOR_HTTP: "true"
    ports:
      - "8080:8080"
      - "16801:16801"
    volumes:
      - /DATA/AppData/$AppID/data:/data
      - /DATA/Downloads/Motrix:/downloads

x-casaos:
  id: com.casa7014.motrix
  main: server
  port_map: "8080"
  index: /
  scheme: http
  title:
    en_US: Motrix
    ar_SA: Motrix
    de_DE: Motrix
    es_ES: Motrix
    fr_FR: Motrix
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.motrix/assets/icon.png
  version: "2.0.0-beta.39"
