version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Apps/Aria2 Pro"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/Aria2"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/Portainer-Business-Edition"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/dispatcharr"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/fing-agent"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/fritzbox-wlan-password-rotator"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/linkstack"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

  - package-ecosystem: "docker"
    directory: "/Apps/motioneye beta"
    schedule:
      interval: "weekly"
    labels:
      - "docker-update"

