version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/Apps/Aria2 Pro"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/Aria2"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/CastSponsorSkip"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/Portainer-Business-Edition"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/fritzbox-wlan-password-rotator"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/linkstack"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Apps/motioneye beta"
    schedule:
      interval: "weekly"
