name: nodecast-tv

services:
  nodecast-tv:
    image: ghcr.io/technomancer702/nodecast-tv:2.1.1@sha256:8fba1ff59b520b0572166a68bb2a6821101dd67a9c2fdd23584c8458520bdfe6
    container_name: nodecast-tv
    restart: unless-stopped
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp

x-casaos:
  id: com.casa7014.nodecast-tv
  main: nodecast-tv
  port_map: "3000"
  index: /
  scheme: http
  title:
    en_US: Nodecast TV
    ar_SA: Nodecast TV
    de_DE: Nodecast TV
    es_ES: Nodecast TV
    fr_FR: Nodecast TV
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.nodecast-tv/assets/icon.png
  version: "2.1.1"
