name: portainer-business-edition
services:
  portainer:
    image: portainer/portainer-ee:2.45.1
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9000
        published: "9000"
        protocol: tcp
      - target: 9443
        published: "9443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: com.casa7014.portainer-business-edition
  main: portainer
  architectures: [amd64, arm64, arm, ppc64le]
  port_map: "9000"
  index: /
  scheme: http
  title:
    en_US: Portainer ( Business Edition )
  author: yassinyl
  developer: Portainer
  category: Others
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Portainer-Business-Edition/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Portainer-Business-Edition/thumbnail.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Portainer-Business-Edition/screenshot-1.png
  description:
    en_US: Lightweight Docker management UI.
  tagline:
    en_US: Lightweight Docker management UI
  version: "2.45.1"
  website: https://www.portainer.io/
  repo: https://github.com/portainer/portainer
  docs: https://docs.portainer.io/
