services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      TZ: Africa/Tunis
      SERVER_ADMIN: admin@example.com
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      LOG_LEVEL: info
      PHP_MEMORY_LIMIT: 256M
      UPLOAD_MAX_FILESIZE: 8M
    ports:
      - target: 80
        published: '8081'
        protocol: tcp
    restart: unless-stopped
    container_name: linkstack
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge
name: linkstack
x-casaos:
  main: linkstack
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.linkstack/assets/icon.png
  title:
    en_US: LinkStack
  port_map: '8081'
  scheme: http
  id: com.casa7014.linkstack
  index: /
  version: 1.0.0
