name: motioneye-beta
services:
  motioneye:
    image: ghcr.io/motioneye-project/motioneye:0.43.1@sha256:f187d072f6d738f84aca95f3d0fe4bdf1de235a7a81e9ec921a0142edc3c716c
    container_name: motioneye-yassinyl
    network_mode: bridge
    restart: unless-stopped
    ports:
      - target: 8765
        published: "8765"
        protocol: tcp
      - target: 9081
        published: "9081"
        protocol: tcp
    environment:
      TZ: $TZ
      PUID: "1000"
      PGID: "1000"
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/etc_motioneye
        target: /etc/motioneye
      - type: bind
        source: /DATA/AppData/$AppID/var_lib_motioneye
        target: /var/lib/motioneye
x-casaos:
  id: com.casa7014.motioneye-beta
  main: motioneye
  port_map: "8765"
  index: /
  scheme: http
  title:
    en_US: MotionEye
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.motioneye-beta/assets/icon.png
  version: "0.43.1"
