services:
  motioneye:
    image: ghcr.io/motioneye-project/motioneye:0.43.1@sha256:f187d072f6d738f84aca95f3d0fe4bdf1de235a7a81e9ec921a0142edc3c716c
    container_name: motioneye-yassinyl
    network_mode: bridge
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 64M
    ports:
      - 8765:8765
      - 9081:9081
    environment:
      - TZ=Africa/Tunis
      - PUID=1000
      - PGID=1000
    volumes:
      - /DATA/AppData/motioneye/etc_motioneye:/etc/motioneye
      - /DATA/AppData/motioneye/var_lib_motioneye:/var/lib/motioneye
name: motioneye-beta
x-casaos:
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.motioneye-beta/assets/icon.png
  main: motioneye
  title:
    en_US: MotionEye
  scheme: http
  port_map: '8765'
  index: /
  id: com.casa7014.motioneye-beta
  version: 0.43.1
