name: pi-hole

services:
  pihole:
    image: pihole/pihole:2025.08.0@sha256:a8de730d1ace99deed4aaf14757d5e5da79b4f2b38565bf8b65f461396157660
    container_name: pihole
    restart: unless-stopped
    ports:
      - target: 53
        published: "53"
        protocol: tcp
      - target: 53
        published: "53"
        protocol: udp
      - target: 80
        published: "80"
        protocol: tcp
    environment:
      TZ: $TZ
      FTLCONF_dns_listeningMode: all
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/etc-pihole
        target: /etc/pihole

x-casaos:
  id: com.casa7014.pi-hole
  main: pihole
  port_map: "80"
  index: /admin/
  scheme: http
  title:
    en_US: Pi-hole
    ar_SA: Pi-hole
    de_DE: Pi-hole
    es_ES: Pi-hole
    fr_FR: Pi-hole
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.pi-hole/assets/icon.svg
  version: 2025.08.0
