name: aria2-pro
services:
  ariang:
    container_name: aria2-ariang
    image: p3terx/ariang:latest
    restart: unless-stopped
    ports:
      - target: 6880
        published: "6880"
        protocol: tcp
    x-casaos:
      ports:
        - container: "6880"
          description:
            en_US: AriaNg WebUI port
  aria2-pro:
    image: p3terx/aria2-pro:202209060423
    container_name: aria2-pro
    restart: unless-stopped
    network_mode: bridge
    environment:
      LISTEN_PORT: "6888"
      PGID: $PGID
      PUID: $PUID
      RPC_PORT: "6800"
      RPC_SECRET: TOKEN
    ports:
      - target: 6800
        published: "6800"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
    x-casaos:
      envs:
        - container: RPC_SECRET
          description:
            en_US: RPC secret key
        - container: RPC_PORT
          description:
            en_US: RPC port
        - container: LISTEN_PORT
          description:
            en_US: BitTorrent listening port
      ports:
        - container: "6800"
          description:
            en_US: RPC port
        - container: "6888"
          description:
            en_US: BitTorrent TCP/UDP port
      volumes:
        - container: /downloads
          description:
            en_US: Download directory
        - container: /config
          description:
            en_US: Configuration directory
x-casaos:
  id: com.casa7014.aria2-pro
  main: aria2-pro
  architectures: [amd64, arm64, arm, "386"]
  port_map: "6800"
  index: /#!/downloading
  scheme: http
  title:
    en_US: Aria2 Pro
  author: yassinyl
  developer: P3TERX
  category: Others
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Aria2%20Pro/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Aria2%20Pro/thumbnail.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Aria2%20Pro/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/Aria2%20Pro/screenshot-2.png
  description:
    en_US: Powerful Aria2 Docker container with AriaNg WebUI.
  tagline:
    en_US: A better Aria2 Docker container
  version: "1.0.0"
  repo: https://github.com/P3TERX/Aria2-Pro-Docker
  docs: https://p3terx.com/archives/docker-aria2-pro.html
