name: fritzbox-wlan-password-rotator
services:
  app:
    image: phipzzz/fritzbox-wlan-password-rotator:1.4.1
    restart: unless-stopped
    network_mode: bridge
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CRONTAB_EXPRESSION: "0 3 * * *"
      FB_ADDRESS: 192.168.178.1
      FB_PASSWORD: ""
      FB_USER: ""
      WEB_PASSWORD: password
      WEB_PUBLIC_ENABLED: "true"
      WEB_PAGE_TITLE: WLAN QR-Code
      WLAN_CONFIGURATION: WLANConfiguration3
      WEB_WELCOME_MESSAGE_CONTENT: welcome
      PW_CHARSET_ASCII_UPPERCASE: "True"
      PW_CHARSET_ASCII_LOWERCASE: "True"
      PW_CHARSET_DIGITS: "True"
      PW_CHARSET_PUNCTUATION: "False"
      WEB_CUSTOM_BACKGROUND: "True"
    ports:
      - target: 5000
        published: "5001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /app/data
      - type: bind
        source: /DATA/AppData/$AppID/background
        target: /app/static/src/img
x-casaos:
  id: com.casa7014.fritzbox-wlan-password-rotator
  main: app
  architectures: [amd64, arm64]
  port_map: "5001"
  index: /
  scheme: http
  title:
    en_US: FritzBox WLAN Password Rotator
    ar_SA: FritzBox WLAN Password Rotator
    de_DE: FritzBox WLAN Password Rotator
    es_ES: FritzBox WLAN Password Rotator
    fr_FR: FritzBox WLAN Password Rotator
  author: yassinyl
  developer: phipzzz
  category: Networking
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/fritzbox-wlan-password-rotator/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/fritzbox-wlan-password-rotator/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/fritzbox-wlan-password-rotator/screenshot-1.png
  description:
    en_US: Automatically rotates the guest WLAN password of a FRITZ!Box and displays credentials and a QR code.
    ar_SA: يغيّر تلقائيًا كلمة مرور شبكة الضيوف في FRITZ!Box ويعرض بيانات الدخول ورمز QR.
    de_DE: Wechselt das Gäste-WLAN-Passwort einer FRITZ!Box automatisch und zeigt Zugangsdaten sowie einen QR-Code an.
    es_ES: Cambia automáticamente la contraseña de la WLAN de invitados de una FRITZ!Box y muestra las credenciales y un código QR.
    fr_FR: Change automatiquement le mot de passe Wi-Fi invité d’une FRITZ!Box et affiche les identifiants et un code QR.
  tagline:
    en_US: Automatically rotate WLAN passwords for FRITZ!Box
    ar_SA: تغيير كلمات مرور WLAN لـ FRITZ!Box تلقائيًا.
    de_DE: WLAN-Passwörter für FRITZ!Box automatisch wechseln.
    es_ES: Rotación automática de contraseñas WLAN para FRITZ!Box.
    fr_FR: Rotation automatique des mots de passe Wi-Fi pour FRITZ!Box.
  version: "1.4.1"
  repo: https://github.com/phipzzz/fritzbox-wlan-password-rotator
