name: yassinyl-linkstack
services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      TZ: 'Africa/Tunis'
      SERVER_ADMIN: 'admin@example.com'
      HTTP_SERVER_NAME: 'example.com'
      HTTPS_SERVER_NAME: 'example.com'
      LOG_LEVEL: 'info'
      PHP_MEMORY_LIMIT: '256M'
      UPLOAD_MAX_FILESIZE: '8M'
    ports:
      - target: 80
        published: '8081'
        protocol: tcp
    restart: unless-stopped
    container_name: linkstack
    deploy:
      resources:
        reservations:
          memory: 256M
    network_mode: bridge

x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: linkstack
  author: yassinyl
  developer: LinkStackOrg
  category: Casa7014
  description:
    en_us: |
      LinkStack is a highly customizable link-sharing platform with an intuitive and easy-to-use user interface. It offers the ultimate solution for creating a personalized and professional profile page. Showcase all your important links in one place and forget the limitation of only one link on social media. Set up your personal site on your server with just a few clicks.
    zh_cn: |
      LinkStack 是一个高度可定制的链接分享平台，拥有直观易用的用户界面。它是创建个性化和专业档案页面的终极解决方案。在一个地方展示你所有重要的链接，忘记社交媒体上一个链接的限制。只需点击几下，即可在您自己的服务器上建立您的个人网站。
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/icon.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-3.png
  tagline:
    en_us: The Ultimate Link Management Solution
    zh_cn: 终极链接管理解决方案
  tips:
    before_install:
      en_us: |
        This application does not have persistent storage set by default, which means you will lose your application data once you reset the container!
        
        You can set up file mounts yourself to achieve persistent configuration directories. For more information, [please refer](https://github.com/LinkStackOrg/linkstack-docker#persistent-storage).
      zh_cn: |
        本应用默认没有设置持久化存储，意味着你一旦重置容器，将丢失应用数据！

        你可以自行设置文件挂载达到持久化配置的目录，更多信息[请参阅](https://github.com/LinkStackOrg/linkstack-docker#persistent-storage)
  title:
    en_us: LinkStack
  store_app_id: yassinyl-linkstack
  port_map: "8081"
  scheme: http
  envs:
    - container: TZ
      description:
        en_us: TimeZone
        zh_cn: 时区
    - container: PHP_MEMORY_LIMIT
      description:
        en_us: PHP memory limit
        zh_cn: PHP内存限制
    - container: UPLOAD_MAX_FILESIZE
      description:
        en_us: Maximum file upload size
        zh_cn: 最大文件上传大小
  persistence_warning: |
    To ensure persistent storage for your data, configure file mounts as suggested in the installation tips above.
