name: linkstack
services:
  linkstack:
    hostname: linkstack
    image: linkstackorg/linkstack:latest
    environment:
      TZ: $TZ
      SERVER_ADMIN: admin@example.com
      HTTP_SERVER_NAME: example.com
      HTTPS_SERVER_NAME: example.com
      LOG_LEVEL: info
      PHP_MEMORY_LIMIT: 256M
      UPLOAD_MAX_FILESIZE: 8M
    ports:
      - target: 80
        published: "8081"
        protocol: tcp
    restart: unless-stopped
    container_name: linkstack
    network_mode: bridge
    x-casaos:
      envs:
        - container: TZ
          description:
            en_US: Time zone
        - container: PHP_MEMORY_LIMIT
          description:
            en_US: PHP memory limit
        - container: UPLOAD_MAX_FILESIZE
          description:
            en_US: Maximum upload size
      ports:
        - container: "80"
          description:
            en_US: LinkStack HTTP port
x-casaos:
  id: com.casa7014.linkstack
  main: linkstack
  architectures: [amd64, arm, arm64]
  port_map: "8081"
  index: /
  scheme: http
  title:
    en_US: LinkStack
  author: yassinyl
  developer: LinkStackOrg
  category: Others
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/icon.png
  thumbnail: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/thumbnail.png
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/yassinyl/casa7014@refs/heads/main/Apps/linkstack/screenshot-3.png
  description:
    en_US: Highly customizable link-sharing platform with an intuitive user interface.
  tagline:
    en_US: The Ultimate Link Management Solution
  version: "1.0.0"
  website: https://linkstack.org/
  repo: https://github.com/LinkStackOrg/linkstack-docker
  docs: https://docs.linkstack.org/
