name: aria2-pro
services:
  ariang:
    container_name: aria2-ariang
    image: p3terx/ariang:latest@sha256:bfebce37079f3bf01e4a37ed192b5e80cbeaaa407f7eebd42c20a078a114ad67
    restart: unless-stopped
    ports:
      - target: 6880
        published: "6880"
        protocol: tcp
  aria2-pro:
    image: p3terx/aria2-pro:202209060423@sha256:41eb2a91901b7b612f7eb87a617ad05aa02e3f7ed0b7e9531e805818608f99ca
    container_name: aria2-pro
    restart: unless-stopped
    network_mode: bridge
    environment:
      LISTEN_PORT: "6888"
      PGID: $PGID
      PUID: $PUID
      RPC_PORT: "6800"
      RPC_SECRET: TOKEN
    ports:
      - target: 6800
        published: "6800"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
x-casaos:
  id: com.casa7014.aria2-pro
  main: ariang
  port_map: "6880"
  index: /
  scheme: http
  title:
    en_US: Aria2 Pro
    ar_SA: Aria2 Pro
    de_DE: Aria2 Pro
    es_ES: Aria2 Pro
    fr_FR: Aria2 Pro
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.aria2-pro/assets/icon.png
  version: "1.0.0"
