services:
  ariang:
    container_name: aria2-ariang
    image: p3terx/ariang:latest@sha256:1b5cc056ff01b8750822ef4d891e28848306c0003dbdaa2aeb91320981614e82
    logging:
      options:
        max-size: 1m
    restart: unless-stopped
    ports:
      - 6880:6880
  aria2-pro:
    environment:
      LISTEN_PORT: '6888'
      PGID: $PGID
      PUID: $PUID
      RPC_PORT: '6800'
      RPC_SECRET: TOKEN
    image: p3terx/aria2-pro:202209060423@sha256:b5e4d914df8a8649ecb19c429347fdb2df78fee97d6ec8331813840b8cf91e7a
    container_name: aria2-pro
    deploy:
      resources:
        reservations:
          memory: 64M
    network_mode: bridge
    ports:
      - target: 6800
        published: '6800'
        protocol: tcp
      - target: 6888
        published: '6888'
        protocol: tcp
      - target: 6888
        published: '6888'
        protocol: udp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/aria2-pro/config
        target: /config
name: aria2-pro
x-casaos:
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.aria2-pro/assets/icon.png
  main: aria2-pro
  title:
    en_US: Aria2 Pro
  scheme: http
  port_map: '6800'
  index: /#!/downloading
  id: com.casa7014.aria2-pro
  version: 1.0.0
