name: aria2-pro
services:
  ariang:
    container_name: aria2-ariang
    image: p3terx/ariang:latest@sha256:dd750181fed3bf8dc5f6f3168b9e3ee3708ca7c415cd3a32a04c5931ebd3e076
    restart: unless-stopped
    ports:
      - target: 6880
        published: "6880"
        protocol: tcp
  aria2-pro:
    image: p3terx/aria2-pro:202209060423@sha256:b121ddfd839a17397238368e1628364f530cdb0e356cc4895d9cd03c99827004
    container_name: aria2-pro
    restart: unless-stopped
    network_mode: bridge
    environment:
      LISTEN_PORT: "6888"
      PGID: $PGID
      PUID: $PUID
      RPC_PORT: "6800"
      RPC_SECRET: TOKEN
    ports:
      - target: 6800
        published: "6800"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
x-casaos:
  id: com.casa7014.aria2-pro
  main: aria2-pro
  port_map: "6800"
  index: /#!/downloading
  scheme: http
  title:
    en_US: Aria2 Pro
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.aria2-pro/assets/icon.png
  version: "1.0.0"
