name: aria2-pro
services:
  ariang:
    container_name: aria2-ariang
    image: p3terx/ariang:latest@sha256:dffd33085d6ce0dbad811ba13336e64dfdbe78ec32be630ea5782fa021063a3c
    restart: unless-stopped
    ports:
      - target: 6880
        published: "6880"
        protocol: tcp
  aria2-pro:
    image: p3terx/aria2-pro:202209060423@sha256:3340a913464f23c18767b33e3cd1031ca5c91b6fa1d1b0282f3f2331ff07df20
    container_name: aria2-pro
    restart: unless-stopped
    network_mode: bridge
    environment:
      LISTEN_PORT: "6888"
      PGID: $PGID
      PUID: $PUID
      RPC_PORT: "6800"
      RPC_SECRET: TOKEN
    ports:
      - target: 6800
        published: "6800"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: tcp
      - target: 6888
        published: "6888"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
x-casaos:
  id: com.casa7014.aria2-pro
  main: ariang
  port_map: "6880"
  index: /
  scheme: http
  title:
    en_US: Aria2 Pro
    ar_SA: Aria2 Pro
    de_DE: Aria2 Pro
    es_ES: Aria2 Pro
    fr_FR: Aria2 Pro
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.aria2-pro/assets/icon.png
  version: "1.0.0"
