name: snikket

services:
  snikket-proxy:
    image: snikket/snikket-web-proxy:stable
    container_name: snikket-proxy
    restart: unless-stopped
    environment:
      SNIKKET_DOMAIN: chat.example.com
      SNIKKET_ADMIN_EMAIL: admin@example.com
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /snikket

  snikket:
    image: snikket/snikket-server:stable
    container_name: snikket
    restart: unless-stopped
    environment:
      SNIKKET_DOMAIN: chat.example.com
      SNIKKET_ADMIN_EMAIL: admin@example.com
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
      - target: 443
        published: "8443"
        protocol: tcp
      - target: 5000
        published: "5000"
        protocol: tcp
      - target: 5222
        published: "5222"
        protocol: tcp
      - target: 5269
        published: "5269"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /snikket

x-casaos:
  id: com.casa7014.snikket
  main: snikket
  port_map: "8080"
  index: /
  scheme: http
  title:
    en_US: Snikket
    ar_SA: سنيكيت
    de_DE: Snikket
    es_ES: Snikket
    fr_FR: Snikket
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.snikket/assets/icon.svg
  version: "stable"
