name: dispatcharr
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.31.0@sha256:c4c84fc4806cac12cf4a33b6df6918b2021e83788f5fe6506430c9ce7538855c
    container_name: dispatcharr
    restart: unless-stopped
    ports:
      - target: 9191
        published: "9191"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data
    environment:
      DISPATCHARR_ENV: aio
      REDIS_HOST: localhost
      CELERY_BROKER_URL: redis://localhost:6379/0
      DISPATCHARR_LOG_LEVEL: info
x-casaos:
  id: com.casa7014.dispatcharr
  main: dispatcharr
  port_map: "9191"
  index: /
  scheme: http
  title:
    en_US: Dispatcharr
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.dispatcharr/assets/icon.png
  version: "0.31.0"
