name: dispatcharr
services:
  dispatcharr:
    image: ghcr.io/dispatcharr/dispatcharr:0.30.0
    restart: unless-stopped
    container_name: dispatcharr
    ports:
      - target: 9191
        published: '9191'
        protocol: tcp
    volumes:
      - /DATA/AppData/$AppID/data:/data
    environment:
      DISPATCHARR_ENV: aio
      REDIS_HOST: localhost
      CELERY_BROKER_URL: redis://localhost:6379/0
      DISPATCHARR_LOG_LEVEL: info
x-casaos:
  id: com.casa7014.dispatcharr
  main: dispatcharr
  index: /
  port_map: '9191'
  scheme: http
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.dispatcharr/assets/icon.png
  title:
    en_US: Dispatcharr
  version: 0.30.0
