name: beszel

services:
  beszel:
    image: henrygd/beszel:0.13.0@sha256:dcd69d620450289b218c1222cefb3c16f63f85d89b2c57abc8985b095faf8e33
    container_name: beszel
    restart: unless-stopped
    ports:
      - target: 8090
        published: "8090"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /beszel_data

x-casaos:
  id: com.casa7014.beszel
  main: beszel
  port_map: "8090"
  index: /
  scheme: http
  title:
    en_US: Beszel
    ar_SA: Beszel
    de_DE: Beszel
    es_ES: Beszel
    fr_FR: Beszel
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.beszel/assets/icon.svg
  version: 0.13.0
