name: bootimus

services:
  bootimus-db:
    container_name: bootimus-db
    image: postgres:16@sha256:485935f94cc7165afa896978809c37b592dc07f0a37d2c8f645f12412d0212c8
    restart: unless-stopped
    environment:
      POSTGRES_USER: bootimus
      POSTGRES_PASSWORD: bootimus
      POSTGRES_DB: bootimus
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/postgres_data
        target: /var/lib/postgresql/data
    networks:
      bootimus_net:
        ipv4_address: 172.23.0.2
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U bootimus
      interval: 10s
      timeout: 5s
      retries: 5

  bootimus:
    container_name: bootimus-server
    image: garybowers/bootimus:latest@sha256:db5aa15bebc2a7a1a8d1afdc19b3d42293b2912470d4753ceded8dda9020affa
    restart: unless-stopped
    depends_on:
      bootimus-db:
        condition: service_healthy

    environment:
      BOOTIMUS_DATA_DIR: /data
      BOOTIMUS_DB_HOST: bootimus-db
      BOOTIMUS_DB_PORT: 5432
      BOOTIMUS_DB_USER: bootimus
      BOOTIMUS_DB_PASSWORD: bootimus
      BOOTIMUS_DB_NAME: bootimus
      BOOTIMUS_DB_SSLMODE: disable
      BOOTIMUS_TFTP_PORT: 69
      BOOTIMUS_HTTP_PORT: 8080
      BOOTIMUS_ADMIN_PORT: 8081
      BOOTIMUS_PROXY_DHCP_ENABLED: "true"

      # CHANGE TO YOUR BOOTIMUS LAN IP
      BOOTIMUS_SERVER_ADDR: 192.168.1.201

    networks:
      bootimus_net:
        ipv4_address: 172.23.0.3

      host_bridge:
        ipv4_address: 192.168.1.201

    ports:
      - target: 69
        published: "69"
        protocol: udp
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 8081
        published: "8081"
        protocol: tcp

    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /data

    cap_add:
      - NET_BIND_SERVICE

networks:
  bootimus_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          gateway: 172.23.0.1

  host_bridge:
    driver: macvlan
    driver_opts:
      # CHANGE TO YOUR LAN INTERFACE
      parent: eth0
    ipam:
      config:
        # CHANGE THESE TO MATCH YOUR LAN
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.201/32

x-casaos:
  id: com.casa7014.bootimus
  main: bootimus
  port_map: "8081"
  index: /
  scheme: http
  title:
    en_US: Bootimus
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.bootimus/assets/icon.png
  version: "0.1.76"
