name: portainer-business-edition
services:
  portainer:
    image: portainer/portainer-ee:2.45.0@sha256:0204286ea7ad9e5fc4ef2e04d4cf6ae23b8d838a165b0ca7fbdad54f618e8918
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9000
        published: "9000"
        protocol: tcp
      - target: 9443
        published: "9443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: com.casa7014.portainer-business-edition
  main: portainer
  port_map: "9000"
  index: /
  scheme: http
  title:
    en_US: Portainer ( Business Edition )
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.portainer-business-edition/assets/icon.png
  version: "2.45.0"
