name: portainer-business-edition
services:
  portainer:
    image: portainer/portainer-ee:2.45.1@sha256:f45ccd1c7b22993f0f2be1094c360f65fabf6b8a7c708bcdc0f23b1e1c704be8
    container_name: portainer
    restart: unless-stopped
    network_mode: bridge
    ports:
      - target: 8000
        published: "8000"
        protocol: tcp
      - target: 9000
        published: "9000"
        protocol: tcp
      - target: 9443
        published: "9443"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
x-casaos:
  id: com.casa7014.portainer-business-edition
  main: portainer
  port_map: "9000"
  index: /
  scheme: http
  title:
    en_US: Portainer ( Business Edition )
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.portainer-business-edition/assets/icon.png
  version: "2.45.1"
