name: lan-orangutan

services:
  lan-orangutan:
    image: ghcr.io/291-group/lan-orangutan:3.3.8@sha256:6cbd001efff691ee926702f51df48f51603016dec57a63fdd144215be19b2c9b
    container_name: lan-orangutan
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
      - NET_BIND_SERVICE
    environment:
      ORANGUTAN_PORT: "291"
      TZ: $TZ
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /var/lib/lan-orangutan
    healthcheck:
      test:
        - CMD
        - wget
        - --no-verbose
        - --tries=1
        - --spider
        - http://127.0.0.1:291/static/orangutan.svg
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
x-casaos:
  id: com.casa7014.lan-orangutan
  main: lan-orangutan
  port_map: "291"
  index: /
  scheme: http
  title:
    en_US: LAN Orangutan
  icon: https://cdn.jsdelivr.net/gh/yassinyl/casa7014@gh-pages/apps/com.casa7014.lan-orangutan/assets/icon.png
  version: "3.3.8"
