name: fing-agent
services:
  fing-agent:
    image: fing/fing-agent:1.1.1@sha256:bdb0a4151db2f898279cf10353bebb6874d55fb5e3cca0f764e339cdad42b2ce
    container_name: FingAgent
    network_mode: host
    cap_add: [NET_ADMIN]
    restart: always
    ports:
      - target: 44444
        published: "44444"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/data
        target: /app/fingdata
x-casaos:
  id: com.casa7014.fing-agent
  main: fing-agent
  port_map: "44444"
  index: /
  scheme: http
  title:
    en_US: Fing Agent
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.fing-agent/assets/icon.png
  version: "1.1.1"
