name: Deploy ZIP to cPanel

on:
  push:
    branches:
      - main
    paths:
      - "Apps/**"
      - "category-list.json"
      - "recommend-list.json"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Create ZIP archive
        run: zip -r casa7014.zip Apps category-list.json recommend-list.json -x "*.png"

      - name: Upload ZIP via FTP
        run: |
          sudo apt-get install -y lftp
          lftp -e "set ftp:ssl-allow no; put casa7014.zip -o casa7014.zip; bye" -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_SERVER }}
