name: Update README App List

on:
  push:
    paths:
      - "Apps/**/docker-compose.yml"

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate app list and update README
        run: |
          list="| Icon | Application | Description |"
          list+="\n|----------------------------------|------------------------------|-------------------------------------------------------------------------------------------------|"

          for file in Apps/*/docker-compose.yml; do
            icon=$(grep 'icon:' "$file" | sed 's/.*icon: //')
            name=$(grep 'title:' -A1 "$file" | grep 'en_us' | sed 's/.*en_us: //')
            desc=$(grep 'description:' -A1 "$file" | grep 'en_us' | sed 's/.*en_us: //')
            if [ -n "$icon" ] && [ -n "$name" ]; then
              list+="\n| <img src=\"$icon\" width=\"50\" height=\"auto\"> | **$name** | $desc |"
            fi
          done

          awk -v list="$list" '
            /<!-- apps:start -->/ { print; print list; in_block=1; next }
            /<!-- apps:end -->/ { in_block=0 }
            !in_block
          ' README.md > README.tmp && mv README.tmp README.md

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "📝 auto: update app list in README"
          git push
