name: fritzbox-wlan-password-rotator
services:
  app:
    image: phipzzz/fritzbox-wlan-password-rotator:1.4.1@sha256:3445a394e846c9581f87018b2929b39f104e4192fd13cd9015d10409366f7387
    restart: unless-stopped
    network_mode: bridge
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
      CRONTAB_EXPRESSION: "0 3 * * *"
      FB_ADDRESS: 192.168.178.1
      FB_PASSWORD: ""
      FB_USER: ""
      WEB_PASSWORD: password
      WEB_PUBLIC_ENABLED: "true"
      WEB_PAGE_TITLE: WLAN QR-Code
      WLAN_CONFIGURATION: WLANConfiguration3
      WEB_WELCOME_MESSAGE_CONTENT: welcome
      PW_CHARSET_ASCII_UPPERCASE: "True"
      PW_CHARSET_ASCII_LOWERCASE: "True"
      PW_CHARSET_DIGITS: "True"
      PW_CHARSET_PUNCTUATION: "False"
      WEB_CUSTOM_BACKGROUND: "True"
    ports:
      - target: 5000
        published: "5001"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /app/data
      - type: bind
        source: /DATA/AppData/$AppID/background
        target: /app/static/src/img
x-casaos:
  id: com.casa7014.fritzbox-wlan-password-rotator
  main: app
  port_map: "5001"
  index: /
  scheme: http
  title:
    en_US: FritzBox WLAN Password Rotator
  icon: https://yassinyl.github.io/casa7014/apps/com.casa7014.fritzbox-wlan-password-rotator/assets/icon.png
  version: "1.4.1"
